export interface USState {
  code: string;
  name: string;
  costOfLivingIndex: number;
}

export const usStates: USState[] = [
  { code: 'AL', name: 'Alabama', costOfLivingIndex: 89.2 },
  { code: 'AK', name: 'Alaska', costOfLivingIndex: 127.1 },
  { code: 'AZ', name: 'Arizona', costOfLivingIndex: 102.2 },
  { code: 'AR', name: 'Arkansas', costOfLivingIndex: 86.9 },
  { code: 'CA', name: 'California', costOfLivingIndex: 149.9 },
  { code: 'CO', name: 'Colorado', costOfLivingIndex: 104.1 },
  { code: 'CT', name: 'Connecticut', costOfLivingIndex: 129.8 },
  { code: 'DE', name: 'Delaware', costOfLivingIndex: 106.7 },
  { code: 'FL', name: 'Florida', costOfLivingIndex: 97.9 },
  { code: 'GA', name: 'Georgia', costOfLivingIndex: 93.4 },
  { code: 'HI', name: 'Hawaii', costOfLivingIndex: 170.0 },
  { code: 'ID', name: 'Idaho', costOfLivingIndex: 94.6 },
  { code: 'IL', name: 'Illinois', costOfLivingIndex: 94.3 },
  { code: 'IN', name: 'Indiana', costOfLivingIndex: 90.4 },
  { code: 'IA', name: 'Iowa', costOfLivingIndex: 90.1 },
  { code: 'KS', name: 'Kansas', costOfLivingIndex: 88.5 },
  { code: 'KY', name: 'Kentucky', costOfLivingIndex: 90.9 },
  { code: 'LA', name: 'Louisiana', costOfLivingIndex: 94.2 },
  { code: 'ME', name: 'Maine', costOfLivingIndex: 106.7 },
  { code: 'MD', name: 'Maryland', costOfLivingIndex: 124.0 },
  { code: 'MA', name: 'Massachusetts', costOfLivingIndex: 131.6 },
  { code: 'MI', name: 'Michigan', costOfLivingIndex: 90.1 },
  { code: 'MN', name: 'Minnesota', costOfLivingIndex: 101.4 },
  { code: 'MS', name: 'Mississippi', costOfLivingIndex: 84.8 },
  { code: 'MO', name: 'Missouri', costOfLivingIndex: 89.9 },
  { code: 'MT', name: 'Montana', costOfLivingIndex: 98.1 },
  { code: 'NE', name: 'Nebraska', costOfLivingIndex: 91.3 },
  { code: 'NV', name: 'Nevada', costOfLivingIndex: 105.0 },
  { code: 'NH', name: 'New Hampshire', costOfLivingIndex: 109.7 },
  { code: 'NJ', name: 'New Jersey', costOfLivingIndex: 125.1 },
  { code: 'NM', name: 'New Mexico', costOfLivingIndex: 91.0 },
  { code: 'NY', name: 'New York', costOfLivingIndex: 139.1 },
  { code: 'NC', name: 'North Carolina', costOfLivingIndex: 94.9 },
  { code: 'ND', name: 'North Dakota', costOfLivingIndex: 95.1 },
  { code: 'OH', name: 'Ohio', costOfLivingIndex: 90.8 },
  { code: 'OK', name: 'Oklahoma', costOfLivingIndex: 87.8 },
  { code: 'OR', name: 'Oregon', costOfLivingIndex: 113.1 },
  { code: 'PA', name: 'Pennsylvania', costOfLivingIndex: 101.7 },
  { code: 'RI', name: 'Rhode Island', costOfLivingIndex: 116.7 },
  { code: 'SC', name: 'South Carolina', costOfLivingIndex: 95.9 },
  { code: 'SD', name: 'South Dakota', costOfLivingIndex: 92.5 },
  { code: 'TN', name: 'Tennessee', costOfLivingIndex: 89.8 },
  { code: 'TX', name: 'Texas', costOfLivingIndex: 91.5 },
  { code: 'UT', name: 'Utah', costOfLivingIndex: 103.4 },
  { code: 'VT', name: 'Vermont', costOfLivingIndex: 115.3 },
  { code: 'VA', name: 'Virginia', costOfLivingIndex: 103.6 },
  { code: 'WA', name: 'Washington', costOfLivingIndex: 110.7 },
  { code: 'WV', name: 'West Virginia', costOfLivingIndex: 93.3 },
  { code: 'WI', name: 'Wisconsin', costOfLivingIndex: 97.3 },
  { code: 'WY', name: 'Wyoming', costOfLivingIndex: 92.4 }
]; 